data_transforms:
  a_min: 0
  a_max: 255
  img_size: 600
  use_random_crop: True
  use_rotation: False
  rotation_angle: 10
  use_saturation: False
  saturation: 2
  use_brightness: False
  brightness: 2
  use_horizontal_flip: True
data:
  name: IDRID
  root_path: '/home/ubuntu/Desktop/Domain_Adaptation_Project/data/IDRID/Train'
  label_list: [1,2,3,4,5]
  label_names: ['Microaneurysms', 'Haemorrhages', 'Hard Exudates', 'Optic Disc', 'Soft Exudates']
  volume_channel: 2
