sam:
  img_size: 1024
  num_classes: 5

img_type: 'images'
arch: "Prompt Adapted SAM"
use_fdn: False

prompts:
  USE_TEXT_PROMPT: True
  USE_IMAGE_PROMPT: True
  LOCATION: 'prepend'
  DROPOUT: 0.1
  NUM_TOKENS: 5

training:
  optimizer: 'adamw'
  lr: 1e-3
  batch_size: 8
  num_epochs: 1000
  schedule_step: 200
  schedule_step_factor: 0.5
  weight_decay: 1e-7
  loss: 'weighted CE+dice'

