data_transforms:
  a_min: 0
  a_max: 255
  img_size: 256
  use_random_crop: False
  use_rotation: False
  rotation_angle: 10
  use_saturation: False
  saturation: 2
  use_brightness: False
  brightness: 2
  use_horizontal_flip: False
data:
  name: CHOLEC 8K
  root_path: '/home/ubuntu/Desktop/Domain_Adaptation_Project/data/cholecSeg8k/archive'
  label_list: [1,2,3,4,5,6,7,8,9,10,11,12]
  label_names: ['Grasper', 'L Hook Electrocautery', 'Liver', 'Fat', 'Gall Bladder','Abdominal Wall','Gastrointestinal Tract','Cystic Duct','Blood','Hepatic Vein', 'Liver Ligament', 'Connective Tissue']
  # label_names: ['Abdominal Wall', 'Blood', 'Connective Tissue', 'Cystic Duct', 'Fat',  'Gall Bladder', 'Gastrointestinal Tract', Grasper', 'Hepatic Vein', 'L Hook Electrocautery', 'Liver', 'Liver Ligament']
  volume_channel: 2

