data_transforms:
  a_min: 0
  a_max: 255
  img_size: 512
  use_random_crop: False
  use_rotation: False
  rotation_angle: 10
  use_saturation: False
  saturation: 2
  use_brightness: False
  brightness: 2
  use_horizontal_flip: False
data:
  name: ENDOVIS
  root_path: '/media/ubuntu/New Volume/jay/endovis17/instrument_1_4_testing/'
  label_list: [1,2]
  label_names: ['road','background']
  volume_channel: 2

