data_transforms:
  a_min: 0
  a_max: 255
  img_size: 256
  use_random_crop: False
  use_rotation: False
  rotation_angle: 10
  use_saturation: False
  saturation: 2
  use_brightness: False
  brightness: 2
  use_horizontal_flip: False
data:
  name: ENDOVIS
  root_path: '/media/ubuntu/New Volume/jay/endovis17/instrument_1_4_testing/'
  label_list: [1,2,3,4,5,6,7,8,9,10]
  label_names: ['background tissue', 'surgical instrument', 'kidney parenchyma', 'covered kidney', 'thread', 'clamps', 'suturing needle', 'suction instrument', 'small intestine','ultrasound probe']
  volume_channel: 2

